version: '4.27.2'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql-1/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
<<<<<<< HEAD
      - POSTGRES_DB=project_hub_db
=======
      - POSTGRES_DB=project_hub_db
>>>>>>> 0b32a9234b7cd6d6d6afb4e1f2aec4c1577129a2
