spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/project_hub_db
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: validate
    show-sql: false
  liquibase:
    change-log: classpath:/db/db.changelog-master.yaml
  mail:
    host: smtp.gmail.com
    port: 587
    username: projecthub.sl.noreply@gmail.com
    password: zmblladkexcstsjt
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        mime:
          charset: UTF
    protocol: smtp
  security:
    jwt:
      secret: 5pAq6zRyX8bC3dV2wS7gN1mK9jF0hL4tUoP6iBvE3nG8xZaQrY7cW2fA
      tokenExpirationTimeInMinutes: 1000
      securityFilterPath: /auth/**

gmail:
  api:
    key: AIzaSyDrnmHJhIH6BrqPega6evohV1CZYqhdNjE
app:
  notification:
    nextMailAttemptDelayInSeconds: 30
    numberOfAttempts: 5
    numberOfThreadsAndMailPerThread: 10
  loginPassAuth:
    resetPasswordTokenExpirationTimeInMinutes: 15
    sysAdminFirstName: admin
    sysAdminLastName: admin
    sysAdminEmail: admin@test.pl
    sysAdminPassword: password123
  cipher:
    secret: XwI7VCDgyojWjS3VNr5ntpx5Ma7XWdb5
    algorithm: AES
    bufferSize: 1024

