package com.sensilabs.projecthub.activity.model;

public enum ActivityType{
    CREATE_USER,
    USER_LOG_IN_SUCCESS,
    USER_LOG_IN_FAILED,
    USER_LOG_OUT,
    DELETE_USER,
    DOCUMENT_OPEN,
    KEY_OPEN,
    DOCUMENT_DOWNLOAD,
    CREATE_PROJECT_MEMBER,
    UPDATE_PROJECT_MEMBER,
    DELETE_PROJECT_MEMBER,
    CREATE_PROJECT_ENVIRONMENT,
    UPDATE_PROJECT_ENVIRONMENT,
    DELETE_PROJECT_ENVIRONMENT,
    UPDATE_PROJECT,
    CREATE_RESOURCE,
    UPDATE_RESOURCE,
    DELETE_RESOURCE
}
